volumes:
  ui-node_modules:
  api:

networks:
  local:
  traefik:
    external: true

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        mail:8025
        deltag:ui
        sql:phpmyadmin
    networks:
    - local
    - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.deltag.rule: Host(`deltag.dev.nathejk.dk`) || HostRegexp(`.+\.deltag\.dev\.nathejk\.dk`)

  ui:
    build:
      context: .
      target: ui-dev
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: "true"
      NODE_ENV: development
      API_BASEURL: http://api.deltag.dev.nathejk.dk
    volumes:
    - ./vue:/app
    - ui-node_modules:/app/node_modules
    depends_on:
    - gw
    networks:
    - local

  api:
    build:
      context: .
      target: base
      dockerfile: docker/Dockerfile
    environment:
      JETSTREAM_DSN: nats://dev.nathejk.dk:4222
      STAN_DSN: stan://dev.nathejk.dk:4222/test-cluster
      DB_DSN: bruger:kodeord@tcp(db:3306)/tilmelding?parseTime=true
      SMS_DSN: cpsms://TOKEN@api.cpsms.dk
      #MONOLITH_DB_DSN_RW: root:ib@tcp(dev.nathejk.dk:3306)/nathejk2018?parseTime=true
      #SENIOR_COUNT: 125
      #GO_BUILD_FLAGS: -race
      SMTP_HOST: mail
      SMTP_PORT: 1025
    volumes:
    - ./go:/app
    - api:/go
    depends_on:
    - gw
    - db
    networks:
    - local

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ib
      MYSQL_DATABASE: tilmelding
      MYSQL_USER: bruger
      MYSQL_PASSWORD: kodeord
      TZ: Europe/Copenhagen
    networks:
    - local

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ib
      PMA_USER: bruger
      PMA_PASSWORD: kodeord
    depends_on:
    - gw
    networks:
    - local

  mail:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    restart: unless-stopped
    networks:
    - local
